import pandas as pd
#Banco de músicas
banco_de_musicas = [
    {"nome": "Bohemian Rhapsody", "artista": "Queen", "ano": 1975, "gênero": "Rock", "subgênero": "Rock Progressivo"},
    {"nome": "Billie Jean", "artista": "Michael Jackson", "ano": 1983, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "Like a Rolling Stone", "artista": "Bob Dylan", "ano": 1965, "gênero": "Rock", "subgênero": "Folk Rock"},
    {"nome": "Imagine", "artista": "John Lennon", "ano": 1971, "gênero": "Pop", "subgênero": "Piano Rock"},
    {"nome": "Thriller", "artista": "Michael Jackson", "ano": 1982, "gênero": "Pop", "subgênero": "Funk"},
    {"nome": "Stairway to Heaven", "artista": "Led Zeppelin", "ano": 1971, "gênero": "Rock", "subgênero": "Rock Progressivo"},
    {"nome": "What's Going On", "artista": "Marvin Gaye", "ano": 1971, "gênero": "R&B", "subgênero": "Soul"},
    {"nome": "Boogie Wonderland", "artista": "Earth, Wind & Fire", "ano": 1979, "gênero": "R&B", "subgênero": "Disco"},
    {"nome": "Hotel California", "artista": "Eagles", "ano": 1976, "gênero": "Rock", "subgênero": "Rock Alternativo"},
    {"nome": "Smells Like Teen Spirit", "artista": "Nirvana", "ano": 1991, "gênero": "Rock", "subgênero": "Grunge"},
    {"nome": "I Want to Hold Your Hand", "artista": "The Beatles", "ano": 1963, "gênero": "Rock", "subgênero": "Rock'n'Roll"},
    {"nome": "Superstition", "artista": "Stevie Wonder", "ano": 1972, "gênero": "R&B", "subgênero": "Funk"},
    {"nome": "I Will Always Love You", "artista": "Whitney Houston", "ano": 1992, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "Every Breath You Take", "artista": "The Police", "ano": 1983, "gênero": "Rock", "subgênero": "New Wave"},
    {"nome": "Johnny B. Goode", "artista": "Chuck Berry", "ano": 1958, "gênero": "Rock", "subgênero": "Rock'n'Roll"},
    {"nome": "Dancing Queen", "artista": "ABBA", "ano": 1976, "gênero": "Pop", "subgênero": "Disco"},
    {"nome": "Sweet Child o' Mine", "artista": "Guns N' Roses", "ano": 1987, "gênero": "Rock", "subgênero": "Hard Rock"},
    {"nome": "Imagine", "artista": "Ariana Grande", "ano": 2019, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "Shape of You", "artista": "Ed Sheeran", "ano": 2017, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "Despacito", "artista": "Luis Fonsi, Daddy Yankee", "ano": 2017, "gênero": "Reggaeton", "subgênero": "Pop Latino"},
    {"nome": "Like a Prayer", "artista": "Madonna", "ano": 1989, "gênero": "Pop", "subgênero": "Pop Rock"},
    {"nome": "Yesterday", "artista": "The Beatles", "ano": 1965, "gênero": "Rock", "subgênero": "Pop Rock"},
    {"nome": "I Will Survive", "artista": "Gloria Gaynor", "ano": 1978, "gênero": "Disco", "subgênero": "Dance"},
    {"nome": "Sweet Caroline", "artista": "Neil Diamond", "ano": 1969, "gênero": "Pop", "subgênero": "Soft Rock"},
    {"nome": "Purple Haze", "artista": "Jimi Hendrix", "ano": 1967, "gênero": "Rock", "subgênero": "Rock Psicodélico"},
    {"nome": "Hips Don't Lie", "artista": "Shakira ft. Wyclef Jean", "ano": 2006, "gênero": "Pop Latino", "subgênero": "Reggaeton"},
    {"nome": "Wannabe", "artista": "Spice Girls", "ano": 1996, "gênero": "Pop", "subgênero": "Dance-Pop"},
    {"nome": "Bad Romance", "artista": "Lady Gaga", "ano": 2009, "gênero": "Pop", "subgênero": "Electropop"},
    {"nome": "Another Brick in the Wall", "artista": "Pink Floyd", "ano": 1979, "gênero": "Rock", "subgênero": "Rock Progressivo"},
    {"nome": "I Feel Good", "artista": "James Brown", "ano": 1965, "gênero": "R&B", "subgênero": "Funk"},
    {"nome": "Drops of Jupiter", "artista": "Train", "ano": 2001, "gênero": "Rock", "subgênero": "Rock Alternativo"},
    {"nome": "Nothing Compares 2 U", "artista": "Sinéad O'Connor", "ano": 1990, "gênero": "Pop", "subgênero": "Rock Alternativo"},
    {"nome": "Waterloo", "artista": "ABBA", "ano": 1974, "gênero": "Pop", "subgênero": "Eurodance"},
    {"nome": "La Bamba", "artista": "Ritchie Valens", "ano": 1958, "gênero": "Rock and Roll", "subgênero": "Chicano Rock"},
    {"nome": "All Star", "artista": "Smash Mouth", "ano": 1999, "gênero": "Rock", "subgênero": "Pop Punk"},
    {"nome": "Livin' on a Prayer", "artista": "Bon Jovi", "ano": 1986, "gênero": "Rock", "subgênero": "Hard Rock"},
    {"nome": "I Gotta Feeling", "artista": "The Black Eyed Peas", "ano": 2009, "gênero": "Pop", "subgênero": "Dance-Pop"},
    {"nome": "Sweet Home Alabama", "artista": "Lynyrd Skynyrd", "ano": 1974, "gênero": "Rock", "subgênero": "Southern Rock"},
    {"nome": "Empire State of Mind", "artista": "Jay-Z ft. Alicia Keys", "ano": 2009, "gênero": "Hip Hop", "subgênero": "Rap"},
    {"nome": "Sweet Dreams (Are Made of This)", "artista": "Eurythmics", "ano": 1983, "gênero": "Pop", "subgênero": "Synthpop"},
    {"nome": "Every Teardrop is a Waterfall", "artista": "Coldplay", "ano": 2011, "gênero": "Rock", "subgênero": "Pop Rock"},
    {"nome": "Crazy", "artista": "Gnarls Barkley", "ano": 2006, "gênero": "Hip Hop", "subgênero": "Soul"},
    {"nome": "Unchained Melody", "artista": "The Righteous Brothers", "ano": 1965, "gênero": "Pop", "subgênero": "Blue-Eyed Soul"},
    {"nome": "Kiss", "artista": "Prince", "ano": 1986, "gênero": "Pop", "subgênero": "Funk"},
    {"nome": "Total Eclipse of the Heart", "artista": "Bonnie Tyler", "ano": 1983, "gênero": "Rock", "subgênero": "Power Ballad"},
    {"nome": "Viva la Vida", "artista": "Coldplay", "ano": 2008, "gênero": "Rock", "subgênero": "Baroque Pop"},
    {"nome": "Man in the Mirror", "artista": "Michael Jackson", "ano": 1988, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "I Can't Get No Satisfaction", "artista": "The Rolling Stones", "ano": 1965, "gênero": "Rock", "subgênero": "Rock and Roll"},
    {"nome": "Radioactive", "artista": "Imagine Dragons", "ano": 2012, "gênero": "Rock", "subgênero": "Indie Rock"},
    {"nome": "Sweet Emotion", "artista": "Aerosmith", "ano": 1975, "gênero": "Rock", "subgênero": "Hard Rock"},
    {"nome": "Don't Stop Believin'", "artista": "Journey", "ano": 1981, "gênero": "Rock", "subgênero": "Arena Rock"},
    {"nome": "Say My Name", "artista": "Destiny's Child", "ano": 1999, "gênero": "R&B", "subgênero": "Hip Hop Soul"},
    {"nome": "Hound Dog", "artista": "Elvis Presley", "ano": 1956, "gênero": "Rock and Roll", "subgênero": "Rockabilly"},
    {"nome": "Sultans of Swing", "artista": "Dire Straits", "ano": 1978, "gênero": "Rock", "subgênero": "Rock Clássico"},
    {"nome": "One", "artista": "U2", "ano": 1991, "gênero": "Rock", "subgênero": "Rock Alternativo"},
    {"nome": "Blue Suede Shoes", "artista": "Elvis Presley", "ano": 1956, "gênero": "Rock and Roll", "subgênero": "Rockabilly"},
    {"nome": "Dancing in the Dark", "artista": "Bruce Springsteen", "ano": 1984, "gênero": "Rock", "subgênero": "Rock Contemporâneo"},
    {"nome": "Somebody to Love", "artista": "Queen", "ano": 1976, "gênero": "Rock", "subgênero": "Rock Progressivo"},
    {"nome": "Royals", "artista": "Lorde", "ano": 2013, "gênero": "Pop", "subgênero": "Indie Pop"},
    {"nome": "Girls Just Want to Have Fun", "artista": "Cyndi Lauper", "ano": 1983, "gênero": "Pop", "subgênero": "New Wave"},
    {"nome": "Eye of the Tiger", "artista": "Survivor", "ano": 1982, "gênero": "Rock", "subgênero": "Hard Rock"},
    {"nome": "Ironic", "artista": "Alanis Morissette", "ano": 1995, "gênero": "Rock", "subgênero": "Alternative Rock"},
    {"nome": "Wuthering Heights", "artista": "Kate Bush", "ano": 1978, "gênero": "Pop", "subgênero": "Art Pop"},
    {"nome": "Piano Man", "artista": "Billy Joel", "ano": 1973, "gênero": "Rock", "subgênero": "Soft Rock"},
    {"nome": "Black", "artista": "Pearl Jam", "ano": 1991, "gênero": "Rock", "subgênero": "Grunge"},
    {"nome": "Don't Speak", "artista": "No Doubt", "ano": 1996, "gênero": "Rock", "subgênero": "Ska Punk"},
    {"nome": "Sweet Caroline", "artista": "Neil Diamond", "ano": 1969, "gênero": "Pop", "subgênero": "Soft Rock"},
    {"nome": "Take on Me", "artista": "a-ha", "ano": 1984, "gênero": "Synthpop", "subgênero": "New Wave"},
    {"nome": "Crazy Little Thing Called Love", "artista": "Queen", "ano": 1979, "gênero": "Rock", "subgênero": "Rockabilly"},
    {"nome": "Clocks", "artista": "Coldplay", "ano": 2002, "gênero": "Rock", "subgênero": "Post-Britpop"},
    {"nome": "With or Without You", "artista": "U2", "ano": 1987, "gênero": "Rock", "subgênero": "Rock Alternativo"},
    {"nome": "Proud Mary", "artista": "Tina Turner", "ano": 1971, "gênero": "R&B", "subgênero": "Soul"},
    {"nome": "More Than a Feeling", "artista": "Boston", "ano": 1976, "gênero": "Rock", "subgênero": "Arena Rock"},
    {"nome": "My Heart Will Go On", "artista": "Celine Dion", "ano": 1997, "gênero": "Pop", "subgênero": "Adult Contemporary"},
    {"nome": "Paint It Black", "artista": "The Rolling Stones", "ano": 1966, "gênero": "Rock", "subgênero": "Psychedelic Rock"},
    {"nome": "Under Pressure", "artista": "Queen & David Bowie", "ano": 1981, "gênero": "Rock", "subgênero": "Art Rock"},
    {"nome": "How Deep Is Your Love", "artista": "Bee Gees", "ano": 1977, "gênero": "Pop", "subgênero": "Disco"},
    {"nome": "Just the Way You Are", "artista": "Bruno Mars", "ano": 2010, "gênero": "Pop", "subgênero": "R&B"},
    {"nome": "Thunderstruck", "artista": "AC/DC", "ano": 1990, "gênero": "Rock", "subgênero": "Hard Rock"},
    {"nome": "Wrecking Ball", "artista": "Miley Cyrus", "ano": 2013, "gênero": "Pop", "subgênero": "Pop Rock"},
    {"nome": "Dancing Queen", "artista": "ABBA", "ano": 1976, "gênero": "Pop", "subgênero": "Disco"},
    {"nome": "Blackbird", "artista": "The Beatles", "ano": 1968, "gênero": "Rock", "subgênero": "Folk Rock"},
    {"nome": "Every Little Thing She Does Is Magic", "artista": "The Police", "ano": 1981, "gênero": "Rock", "subgênero": "New Wave"},
    {"nome": "Rolling in the Deep", "artista": "Adele", "ano": 2010, "gênero": "Pop", "subgênero": "Soul"},
    {"nome": "Blinding Lights", "artista": "The Weeknd", "ano": 2019, "gênero": "Pop", "subgênero": "Synthwave"},
    {"nome": "Ain't No Mountain High Enough", "artista": "Marvin Gaye & Tammi Terrell", "ano": 1967, "gênero": "R&B", "subgênero": "Soul"},
    {"nome": "The Sound of Silence", "artista": "Simon & Garfunkel", "ano": 1964, "gênero": "Folk Rock", "subgênero": "Rock Acústico"},
    {"nome": "Karma Police", "artista": "Radiohead", "ano": 1997, "gênero": "Rock", "subgênero": "Art Rock"},
    {"nome": "Someone Like You", "artista": "Adele", "ano": 2011, "gênero": "Pop", "subgênero": "Soul"},
    {"nome": "Shallow", "artista": "Lady Gaga & Bradley Cooper", "ano": 2018, "gênero": "Pop", "subgênero": "Country Pop"},
    {"nome": "Waterfalls", "artista": "TLC", "ano": 1994, "gênero": "R&B", "subgênero": "Hip Hop Soul"},
    {"nome": "Satisfaction", "artista": "Benny Benassi", "ano": 2002, "gênero": "Eletrônica", "subgênero": "Electro House"},
    {"nome": "Mamma Mia", "artista": "ABBA", "ano": 1975, "gênero": "Pop", "subgênero": "Disco"},
    {"nome": "Roll Over Beethoven", "artista": "Chuck Berry", "ano": 1956, "gênero": "Rock and Roll", "subgênero": "Rockabilly"},
    {"nome": "Bad Blood", "artista": "Taylor Swift ft. Kendrick Lamar", "ano": 2015, "gênero": "Pop", "subgênero": "Hip Hop"},
    {"nome": "Under the Bridge", "artista": "Red Hot Chili Peppers", "ano": 1992, "gênero": "Rock", "subgênero": "Alternative Rock"},
    {"nome": "Flashdance... What a Feeling", "artista": "Irene Cara", "ano": 1983, "gênero": "Pop", "subgênero": "Synthpop"},
    {"nome": "No Scrubs", "artista": "TLC", "ano": 1999, "gênero": "R&B", "subgênero": "Hip Hop Soul"},
    {"nome": "Chandelier", "artista": "Sia", "ano": 2014, "gênero": "Pop", "subgênero": "Electropop"},
    {"nome": "American Pie", "artista": "Don McLean", "ano": 1971, "gênero": "Folk Rock", "subgênero": "Rock Folclórico"}]
"""# Criar um DataFrame pandas
df = pd.DataFrame(banco_de_musicas)

# Selecionar músicas do mesmo subgênero (por exemplo, "Rock Progressivo")
genero_selecionado = "Rock"
musicas_mesmo_genero = df[df["gênero"] == genero_selecionado]

# Exibir as músicas do mesmo subgênero
print(musicas_mesmo_genero)
"""